services:
  prefect-postgres:
    image: postgres:latest
    container_name: prefect-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - prefectdb:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 60s
      timeout: 10s
      retries: 5
    networks:
      # Connects to the custom bridge network for inter-service communication.
      - prefect-network

  prefect-server:
    build:
      context: ./prefect-server
      dockerfile: Dockerfile
    container_name: prefect-server
    restart: always
    depends_on:
      - prefect-postgres
    networks:
      # Connects to the custom bridge network for inter-service communication.
      - prefect-network

  prefect-nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - prefect-server
    networks:
      # Connects to the custom bridge network for inter-service communication.
      - prefect-network
volumes:
  prefectdb:

networks:
  # Defines a custom bridge network, allowing services to communicate using their service names
  # (e.g., http://prefect-server:4200 from Nginx).
  prefect-network: