debug_mode=true
logging.level="DEBUG"

# Auth
server.api.auth_string="dev:TopSecretPassword2"

# DB Connection
server.database.connection_url="postgresql+asyncpg://postgres:yourTopSecretPassword@prefect-postgres:5432/prefect"

# API
## The API’s host address
server.api.host="prefect-server"
server.api.port=4200

# https://docs-3.prefect.io/v3/api-ref/settings-ref#api-url-2
#
server.ui.api_url="prefect-server/api"