# Auth
server.api.auth_string="dev:TopSecretPassword2"

# DB Connection
server.database.connection_url="postgresql+asyncpg://postgres:yourTopSecretPassword@prefect-postgres:5432/prefect"

# API
## The API’s host address
## https://docs-3.prefect.io/v3/api-ref/settings-ref#host-2
server.api.host="0.0.0.0"
server.api.port=4200

# PREFECT_UI_URL
# https://docs-3.prefect.io/v3/api-ref/settings-ref#ui-url
ui_url="http://localhost/"

# PREFECT_UI_API_URL, PREFECT_SERVER_UI_API_URL
# https://docs-3.prefect.io/v3/api-ref/settings-ref#api-url-2
server.ui.api_url="http://localhost/api"