# Auth
server.api.auth_string="dev:TopSecretPassword2"

# DB Connection
server.database.connection_url="postgresql+asyncpg://postgres:yourTopSecretPassword@prefect-postgres:5432/prefect"

#------------------------------------
# Default is "127.0.0.1", loopback, implies the server is listening only on localhost
# So when in the docker, this implies that the server is not accessible outside
# Even if you expose the 4200 port.
server.api.host="0.0.0.0"
server.api.port=4200
# 0.0.0.0 implies that the server is listening on all network interfaces on port 4200
#------------------------------------

# server.ui.api_url defaults to http://127.0.0.1:4200/api
# This makes the UI want to connect to the same machine on which you are accessing the UI
# The API is not running there.
# It should point to the IP that is accessible from outside
# When we close the port, it needs to go to the proxy which is listening on port 80.
server.ui.api_url="http://192.168.8.135/api"
# Once it has been hosted, we will need to point it to the correct domain name
# When running on EC2, we will need to point to the IP that we get

ui_url="http://192.168.8.135"